### PR TITLE
Rerun sonobuoy

### LINKED ISSUE #181: sonobuoy-test-agent: rerun failed tests
We need to to be able to support the ability to rerun failed tests from a sonobuoy test results archive.

### PR DESCRIPTION
**Pull request by ecpullen**
**Issue number:**

Closes #181 

**Description of changes:**

Adds a function `rerun_failed` to the `Runner` trait. After `run` is called, `rerun_failed` will be called up to `retries` times or `Outcome::Pass` is returned.

**Testing done:**

Forced a sonobuoy test to fail and the test was properly rerun.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

File: agent/test-agent/src/lib.rs [hunk 1]
```diff
@@ -61,6 +62,15 @@ pub trait Runner: Sized {
     /// an error.
     async fn run(&mut self) -> Result<TestResults, Self::E>;
 
+    /// Rerun a failed test.
+    async fn rerun_failed(
+        &mut self,
+        prev_test_result: &TestResults,
+    ) -> Result<TestResults, Self::E> {
+        info!("Tried to rerun test, but no retry method was defined.");
+        Ok(prev_test_result.clone())
```
Comment (webern) [inline agent/test-agent/src/lib.rs]: I don't think this is the right thing to return. It should be something like:

`TestResults{ failed: 1, passed: 0, failed_tests: ["No retry_failed method defined"] }`

File: testsys/src/run_aws_k8s.rs [hunk 2]
```diff
@@ -129,6 +129,10 @@ pub(crate) struct RunAwsK8s {
     #[structopt(long)]
     keep_instance_provider_running: bool,
 
+    /// Allow the sonobuoy test agent to rerun failed test.
+    #[structopt(long)]
+    allow_retries: Option<u32>,
```
Comment (webern) [inline testsys/src/run_aws_k8s.rs]: Not sure my suggestion is the best but `--allow-retries` sounds like a boolean.

```suggestion
    retry_failed_attempts: Option<u32>,
```

File: testsys/src/run_vmware.rs [hunk 3]
```diff
@@ -142,6 +142,10 @@ pub(crate) struct RunVmware {
     #[structopt(long)]
     keep_instance_provider_running: bool,
 
+    /// Allow the sonobuoy test agent to rerun failed test.
+    #[structopt(long)]
+    allow_retries: Option<u32>,
```
Comment (webern) [inline testsys/src/run_vmware.rs]: Same comment as elsewhere, the name sounds like a boolean.

File: agent/test-agent/src/lib.rs [hunk 4]
```diff
@@ -100,9 +110,15 @@ pub trait Client: Sized {
...
     async fn keep_running(&self) -> Result<bool, Self::E>;
 
+    /// Determine the number of retries the agent is expected to perform for failed tests.
+    async fn retries(&self) -> Result<u32, Self::E>;
+
     /// Set the appropriate status field to represent that the test has started.
     async fn send_test_starting(&self) -> Result<(), Self::E>;
 
+    /// Set the appropriate status fields once the test has `TestResults` available.
+    async fn send_test_results(&self, results: TestResults) -> Result<(), Self::E>;
```
Comment (webern) [inline agent/test-agent/src/lib.rs]:
```suggestion
    /// Add a TestResults object to the CRDs array of TestResults without signaling that the test
    /// is complete. This is used to send TestResults when some failures have occured and we are
    /// going to re-run the failed test cases.
    async fn send_test_results(&self, results: TestResults) -> Result<(), Self::E>;
```

File: agent/test-agent/src/lib.rs [hunk 5]
```diff
@@ -100,9 +110,15 @@ pub trait Client: Sized {
...
+
     /// Set the appropriate status fields once the test has finished.
```
Comment (webern) [inline agent/test-agent/src/lib.rs]:
```suggestion
    /// Add a TestResults object to the array of TestResults in the test CRD and set the task state
    /// as `Done` indicating that no more retries or testing will occur.

```

File: bottlerocket/agents/src/bin/sonobuoy-test-agent/main.rs [hunk 6]
```diff
@@ -95,6 +95,33 @@ impl test_agent::Runner for SonobuoyTestRunner {
         .await
     }
 
+    async fn rerun_failed(&mut self, _prev_results: &TestResults) -> Result<TestResults, Self::E> {
+        // Set up the aws credentials if they were provided.
+        if let Some(aws_secret_name) = &self.aws_secret_name {
+            setup_test_env(self, aws_secret_name).await?;
+        }
+
+        if let Some(wireguard_secret_name) = &self.wireguard_secret_name {
```
Comment (webern) [inline bottlerocket/agents/src/bin/sonobuoy-test-agent/main.rs]: I don't think this needs to be done again, does it?

**Comment by ecpullen** [comment]
^ rebase to develop

File: agent/test-agent/src/lib.rs (hunk 5 above)
Comment (webern) [reply agent/test-agent/src/lib.rs]: @ecpullen This suggestion is on a line that is otherwise unchanged. Not sure if you saw it.

**Review by webern — APPROVED** [review]

File: agent/test-agent/src/agent.rs [hunk 7]
```diff
@@ -93,6 +94,37 @@ where
             }
         };
 
+        // If we are unable to get the number of retries it is safer to assume it is zero
+        // then to error.
+        let retries = self.client.retries().await.unwrap_or_default();
+        let mut retry_count = 0;
+        while test_results.outcome != Outcome::Pass && retry_count < retries {
+            info!("Test did not pass, retrying ...");
```
Comment (etungsten) [inline agent/test-agent/src/agent.rs]: nit: might be a good idea to log the number of retries/retry # we're about to attempt.

**Review by etungsten — APPROVED** [review]
Nice job. Can you also show in the testing description what `testsys status` shows for a test that went through multiple retries?
