### PR TITLE
cli: `restart test`

### LINKED ISSUE #340: cli: restart failed tests
If a test fails due to, e.g. AWS SDK throttling... or for any other reason where we don't care about preserving the state of the failed test run, the CLI could "restart" the test by deleting and recreating the Test CRD (without deleting the resources)

### PR DESCRIPTION
**Pull request by ecpullen**
**Issue number:**

Closes #340 

**Description of changes:**

Adds `testsys restart test <test-name>`. This command deletes the test object and then re-creates it.

**Testing done:**

Ran `testsys run aws-k8s ...` and after test completion used `testsys restart test ...` and the sonobuoy test was deleted and a new one was started.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

File: testsys/src/restart_test.rs [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+    pub(crate) async fn run(&self, k8s_client: Client) -> Result<()> {
+        let test_client = TestClient::new_from_k8s_client(k8s_client.clone());
+        let mut test = test_client
+            .get(&self.test_name)
+            .await
+            .context(error::GetSnafu {
+                what: self.test_name.clone(),
+            })?;
+        // Created objects are not allowed to have `resource_version` set.
+        test.metadata.resource_version = None;
```
Comment (webern) [inline testsys/src/restart_test.rs:25]: You also need to set `test.status` to `None`.

**Review by webern — CHANGES_REQUESTED** [review]
Nice, that was fast. We need to obliterate the `status` otherwise I think the controller wouldn't see this as a new test.

File: testsys/src/restart_test.rs (hunk 1 above)
Comment (ecpullen) [reply testsys/src/restart_test.rs:25]: The status is automatically reset. We can do it explicitly if you'd prefer.

Comment (webern) [reply testsys/src/restart_test.rs:25]: Oh. Well, I guess it would make me feel better to see it even if it is not strictly necessary.

**Comment by ecpullen** [comment]
^ reset `test.status`

**Review by webern — APPROVED** [review]

**Review by etungsten — APPROVED** [review]
